---

- name: install software-properties-common
  apt: name=software-properties-common state=present

- name: add apt repository
  shell: apt-add-repository -y ppa:nginx/development

- name: install nginx
  apt: name=nginx state=present update_cache=yes

